### ISSUE TITLE
JavaScript running on Photino will not get any keyboard events until window is clicked

### ISSUE THREAD

**Issue by RonenNess** [tryphotino/photino.NET#100]
Hello,

As the title says - no matter what I do, until clicking the Photino window, no keyboard events will be fired. I even tried to force windows to focus on the window (using the window handle) but it didn't work.

Any way around this?

Thanks! :)

**Comment by MikeYeager** [comment]
@RonenNess Apparently, focus is set to the web control on Mac and Linux automatically, but not in Windows. We seem to have fixed that just in time for our next release (in the next few days).

**Comment by RonenNess** [comment]
That's great, thanks!
Can you please add a method to focus on the WebView window while at it? Its a very useful functionality and sounds like something you could do from your end.

Thanks :)

**Comment by MikeYeager** [comment]
@RonenNess That is actually what fixed the keyboard event issue. On Mac and Linux, the control gets focus by default since it's the only control on the form. On Windows, we had to explicitly set focus on it.
