### ISSUE TITLE
how to disable cors?

### ISSUE THREAD

**Issue by smersh1307n2** [tryphotino/photino.NET#101]
Access to fetch at 'file:///D:/Visual%20Studio%20Projects/Hydra/Hydra/bin/Debug/net6.0/wwwroot/_framework/blazor.boot.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, chrome-untrusted, https, isolated-app.

To solve this problem in nwjs, you can use chromium-args --disable-web-security.
how to disable cors in photino.NET ?

**Comment by RonenNess** [comment]
Hi @smersh1307n2  see this, might help you out: #96

**Comment by philippjbauer** [comment]
@smersh1307n2 We just released a new version of the Photino.Native, Photino.NET and Photino.Sample projects. Photino.NET now includes an optional file server based on ASP.NET Kestrel. Please refer to the `Photino.HelloPhotino.StaticFileServer` sample for usage: [Program.cs](https://github.com/tryphotino/photino.Samples/blob/546ef6fd409d9e20fdde9ff468ec2fd37537ad95/Photino.HelloPhotino.StaticFileServer/Program.cs#L11-L13).

When using this file server your CORS issues should disappear. The underlying web view Photino uses across all platforms does not provide a way to disable CORS like Chromium does.
