### ISSUE TITLE
Where can we find documentation of changes between versions?

### ISSUE THREAD

**Issue by RonenNess** [tryphotino/photino.NET#102]
Didn't find here nor on Nuget but maybe I just missed something.

Also, may I suggest using github Releases instead of just tags (a release is a Tag + release data). its super convenient and don't cost anything + you can add changes list to the release comment for extra visibility.

https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

Thanks for this great lib!

**Comment by philippjbauer** [comment]
Thank you, I created the latest release notes here: https://github.com/tryphotino/photino.NET/releases/tag/v2.2.2
