### ISSUE TITLE
On MacOS with .Net 6 - Unhandled exception. System.DllNotFoundException: Unable to load shared library 'Photino.Native' or one of its dependencies

### ISSUE THREAD

**Issue by richardschoen** [tryphotino/photino.NET#103]
```Hardware is Mac M1 running macOS 12.4```

Here's what I did:
```
dotnet new photinoapp -o MyPhotinoApp
cd MyPhotinoApp
dotnet run]
```
Here's the result:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'Photino.Native' or one of its dependencies. 
In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(libPhotino.Native, 0x0001): tried: 'libPhotino.Native' (no such file), '/usr/local/lib/libPhotino.Native' (no such file), 
'/usr/lib/libPhotino.Native' (no such file), '/Users/richard/Documents/MyPhotinoApp/libPhotino.Native' (no such file)
   at PhotinoNET.PhotinoWindow.Photino_register_mac()
   at PhotinoNET.PhotinoWindow.<>c.<.ctor>b__196_1()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow..ctor(PhotinoWindow parent)
   at HelloPhotinoApp.Program.Main(String[] args) in /Users/richard/Documents/MyPhotinoApp/Program.cs:line 18
```

There is no file named ```libPhotino.Native```.

I did copy the ```Photino.Native.dylib``` into the app bin folder. No luck. 

I also copied ```Photino.Native.dylib``` to the app folder as ```libPhotino.Native``` and still no luck. 

Works fine in Windows. 

Rosetta is loaded.

I'm new to .Net 6 on macOS M1.

Thoughts on the issue ?

User error. Something else ? :-)

**Comment by richardschoen** [comment]
I also opened the project in VS for Mac V17.0 and got same error. Compiles but won't run.

**Comment by richardschoen** [comment]
The issue may possibly be related to the dylib requiring x86_64 vs arm64e.

I tried installing the macOS x64 .Net runtimes. Still no luck yet.

**Comment by philippjbauer** [comment]
@richardschoen We have just (today) released a new template package that makes use of the latest updates across all Photino packages. This includes the latest Photino.Native package with ARM64 support across all platforms.

Reinstall the templates with `dotnet new --install TryPhotino.VSCode.Project.Templates::2.2.0`

**Comment by richardschoen** [comment]
@philippjbauer Thanks. I can confirm it works. Looking forward to building more with Photino.
