### ISSUE TITLE
Move PhotinoServer.NET to the separate package

### ISSUE THREAD

**Issue by aesopov** [tryphotino/photino.NET#104]
Currently Photino.NET project is based on Microsoft.NET.Sdk.Web. It means, even if Photino-based application doesn't use `PhotinoServer.CreateStaticFileServer(...)`, it still depends on lots of asp.net libraries. 
When I build HelloWorld app in a self-contained mode, the resulting folder size is about 97 megabytes.
In my project I use custom scheme handler to host application resources, so I don't need to use PhotinoServer. However, when I run `dotnet publish -r osx-arm64 --self-contained`, I'm getting dozens of "Microsoft.AspNetCore.*.dll" files.

Does it make sense to split PhotinoServer and Photino core into separate nuget packages?

Thank you.

**Comment by philippjbauer** [comment]
@misupov Thank you, this is a good suggestion and we will work to implement it that way.
