### ISSUE TITLE
Very odd window redraw slowness on Ubuntu due to svg graphic in demo app.

### ISSUE THREAD

**Issue by raddevus** [tryphotino/photino.NET#111]
When I run the sample Photino.NET app which includes the graphic photino-logo.svg all the windows on my computer suddenly redraw super slowly.  

I've created a video of the windows moving & being redrawn on my computer running Ubuntu 22.04.1 and you can see the cursor which has grabbed a window and is moving it and then only after a second or two does the window finally redraw.
I've posted that video to [youtube so you can watch it](https://youtu.be/bmGm4ZukAWs).

**I Understand This May Seem Like a System Issue**
I have pasted the details of my robust desktop hardware below & my fairly decent GPU below.
Please check the "What I Have Tried" section to see that I've attempted to show root cause for this issue.
I understand this may also be a problem with WebView2 rendering engine or something.

**What I Have Tried**
I started noticing the window redraw slowness when I ran the basic Photino.NET sample app but I still wondered if this could be the thing that is making this occur so I tried a few tests.
1. Started / Stopped demo photino app multiple times.  Each time when app is running slow redraw occurs.  As as soon as I stop the demo app my windows redraw super fast.
2. Loaded the index.html that is used in the demo app in my default (Firefox browser*) This page displays the SVG graphic and when it loads in Firefox I do not see any window redrawing slowness.
3. Removed the link to the SVG graphic and ran the demo app --  This resolved the situation!  The demo app loaded but when I drag windows around my system they redraw extremely fast (completely normally).
4. I added the SVG graphic back in and ran the demo app again -- Problem came back!  The demo app loaded and when I dragged windows it was slow again (as shown in the video).  **This seems to be root cause**.
5. As I was doing all these tests I watched CPU via CPU monitor but never saw any indication of huge processor or memory use.  Nor did I see other performance problems.  This was all related to redraw of windows.  

**My Hardware**
![image](https://user-images.githubusercontent.com/16722666/204579278-8525dccf-ebd6-40f7-a121-9e21b3b98d4f.png)

**My Browser Info**
![image](https://user-images.githubusercontent.com/16722666/204579833-e11c9cd1-8b28-4d2a-82f0-763104b5cd2f.png)

**Comment by MikeYeager** [comment]
@raddevus We ran into similar issues and not just on Ubuntu. It seemed to be an issue with the animated Photino logo we used in the samples. We recently replaced the image with a (non-animated) .PNG version of the logo. Can you confirm that you're experiencing this issue with the animated Photino logo?

**Comment by raddevus** [comment]
> Can you confirm that you're experiencing this issue with the animated Photino logo?

That's correct, it is related to the animated Photino logo.  
If I remove it or use a different image then I no longer see the issue.  Thanks
