### ISSUE TITLE
PhotinoWindow SetSize doesn't work

### ISSUE THREAD

**Issue by Jinjinov** [tryphotino/photino.NET#113]
Steps to reproduce:

1. open https://github.com/tryphotino/photino.Blazor/tree/master/Samples/Photino.Blazor.Sample
2. add `app.MainWindow.SetSize(800, 600);` to `Main` in `Program.cs`
3. run in Windows, Linux, macOS

`app.MainWindow.SetWidth(800);` and `app.MainWindow.SetHeight(600);` also don't work.

In Windows, the size is 1500x1000, and in Linux the size is 100x100 which is very problematic.

**Comment by MikeYeager** [comment]
@Jinjinov The window will open at the OS default windows size and position unless you call .SetUseOsDefaultSize(false) (or the similar call for window position).

**Comment by Jinjinov** [comment]
Thank you!

I would suggest you add `SetUseOsDefaultSize(false)` to your `class PhotinoBlazorApp` in the `Photino.Blazor` project:

```
            WindowManager = Services.GetService<PhotinoWebViewManager>();

            MainWindow
                .SetTitle("Photino.Blazor App")
                .SetUseOsDefaultLocation(false)
                .SetWidth(1000)
                .SetHeight(900)
                .SetLeft(450)
                .SetTop(100);

            MainWindow.RegisterCustomSchemeHandler(PhotinoWebViewManager.BlazorAppScheme, HandleWebRequest);
```
