### ISSUE TITLE
Gamepad stopped working

### ISSUE THREAD

**Issue by RonenNess** [tryphotino/photino.NET#114]
Hi,

Gamepad used to work but suddenly it stopped working. I'm not sure if the issue is with Photino or with the native WebView itself (maybe something updated there that needs an update from Photino side as well) but here's a super simple demo to illustrate the issue:

**wwwroot/index.html:**

```html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <script>
        window.addEventListener("gamepadconnected", (e) => {
            alert("CONNECTED!");
            console.log("Gamepad connected at index %d: %s. %d buttons, %d axes.",
                e.gamepad.index, e.gamepad.id,
                e.gamepad.buttons.length, e.gamepad.axes.length);
        });
    </script>
</body>
</html>
```

**Program.cs**

```cs
using PhotinoNET;
using System.Drawing;

namespace HelloPhotino.ThreeD
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            string windowTitle = "Gamepad Test";
            var window = new PhotinoWindow()
                .SetTitle(windowTitle)
                .SetUseOsDefaultSize(false)
                .SetSize(new Size(700, 525))
                .Center()
                .SetResizable(false)
                .Load("wwwroot/index.html"); 
            window.WaitForClose();
        }
    }
}
```

If you run this in Photino, connect a gamepad, and try to use it, nothing happens.
If you start the exact same HTML either with a static files server or by serving it from filesystem (ie with 'file:///'), you'll see that once you use a gamepad, you see an alert saying "CONNECTED!" and details in the console log.

Now to clarify, its not just the gamepad event not firing, using navigator.getGamePads() or anything gamepad-related don't work either. As if it is no longer recognized (and it used to work perfectly in the past).

Can you please check?

Thanks :)

**Comment by RonenNess** [comment]
Seems to be issue with WebView in general and not Photino:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/3025

**Comment by ottodobretsberger** [comment]
Correct, as @RonenNess  mentioned this seems to be an issue with WebView2. Please follow the thread he linked above to see if/when it gets resolved. There's an explicit mention of Photino in the discussion thread already as well, as far as I have seen.
