### ISSUE TITLE
true chromless mode without border

### ISSUE THREAD

**Issue by GermanJack** [tryphotino/photino.NET#115]
How to turn off the white border when setting the chromless mode?

**Comment by philippjbauer** [comment]
Hi @GermanJack, can you explain a little bit more?

Let us know fore example, the OS you are targeting, a screenshot of the problem and relevant code you are using. This will help us understand your problem

**Comment by GermanJack** [comment]
I am on Windows11.
I want to have a borderless Chromless mode.
Is there a possibility to turn the border off? 
Here a screenshot:
![tng1C1d3bb](https://user-images.githubusercontent.com/46387725/210011781-8de973ee-808a-449c-a8fa-eb91b73a1c1c.png)

I tested also my application on Debian11.
There I do not have this border.

**Comment by GermanJack** [comment]
Just checked Windows10.
There I also get this border.
