### ISSUE TITLE
Rendering to a texture (similar to CefSharp Offscreen rendering)

### ISSUE THREAD

**Issue by clibequilibrium** [tryphotino/photino.NET#122]
Hello,

Is it possible to render photino to a texture ?
My use case is a Game Engine and I would like to integrate photino in a GUI window to allow web-browsing and multi-viewport via imgui + SDL.

I currently see the requirement is to have WinForms running to display webview, I can see a possibility of intercepting the back-buffer of winforms and render it in a window, but have you considered it?

Thank you.

**Comment by ottodobretsberger** [comment]
Hello.
For this scenario it doesn't sound like Photino would be an ideal fit. 
We're not very familiar with the technologies you're using for your game development, but it seems like the setup is dependent on Windows (not cross platform) and a simpler webview integration without the Photino wrapper would be more beneficial. Photino in essence is not a browser alternative.

**Comment by clibequilibrium** [comment]
> Hello. For this scenario it doesn't sound like Photino would be an ideal fit. We're not very familiar with the technologies you're using for your game development, but it seems like the setup is dependent on Windows (not cross platform) and a simpler webview integration without the Photino wrapper would be more beneficial. Photino in essence is not a browser alternative.

Thank you for your reply, 

I was looking at Photino primarily because of its cross-platform nature. CefSharp is Windows only, while imgui, SDL can run anywhere. My question was poorly phrased, the better way would be:

Does Photino team plans to support off screen rendering, so web view of Photino can be rendered in 2D, 3D applications?

**Comment by rmannjbs** [comment]
If you want to Render a browser to a texture to use web UI tech to build things for gaming, there is a product specifically designed for that called UltraLight UX, over here: https://github.com/ultralight-ux/Ultralight
