### ISSUE TITLE
Crash on linux when i set window.SetTopMost(true)

### ISSUE THREAD

**Issue by dryerem19** [tryphotino/photino.NET#133]
Hi, for the sake of convenience during development, I'm trying to make my window always on top of other windows. This works fine on Windows, but causes a crash on Linux.
Crash happens when I call window.WaitForClose() and get "Process finished with exit code 139."

I am using Fedora Linux 36 with KDE Plasma 5.27.1 on X11

**Comment by ottodobretsberger** [comment]
Thank you for mentioning this. 
Our Linux setup is based on the newest Ubuntu distribution where this did not seem to be an issue. We will look into it again to verify. But unfortunately, if for some reasons different distributions do in fact behave differently, it would be too much effort to verify all functionality on all Linux distributions, all the time.

**Comment by jjolidon** [comment]
This is also the case on Raspberry Pi OS (based on Debian Bookworm)

**Comment by philippjbauer** [comment]
Fixed with https://github.com/tryphotino/photino.Native/commit/fee5803aa73762a61ecdc62bafae0818e8487fbe will be added in next release
