### ISSUE TITLE
how to hide status bar at the bottom left?

### ISSUE THREAD

**Issue by zxyao145** [tryphotino/photino.NET#134]
Is it possible to hide the status bar at the bottom left?

https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isstatusbarenabled?view=webview2-dotnet-1.0.1661.34

**Comment by MikeYeager** [comment]
![image](https://user-images.githubusercontent.com/7063813/231799247-8c53cd2c-6573-46a9-ae24-d78699c3144b.png)
Are you asking about where it shows the URL when hovering over a link? I believe this is only on Windows, so the setting may not apply to Mac or Linux.

**Comment by zxyao145** [comment]
@MikeYeager yes, is it possible to close this status bar?

**Comment by CypherPotato** [comment]
nothing?

**Comment by ottodobretsberger** [comment]
Theoretically, yes. I am sure it is possible. We just do not have had the time to look at each individual OS, since there wouldn't be a blanket solution for all. We will label it as an enhancement request.

**Comment by philippjbauer** [comment]
@zxyao145

We added a way to pass init flags to the browser control in Photino.NET v2.5.0 (just released). I'm not sure if there is a flag that can modify this behavior through this but you can certainly have a look here (https://peter.sh/experiments/chromium-command-line-switches/) or search online for a corresponding flag and set it like so:

```cs
string browserControlInitParams = string.Empty;

if (PhotinoWindow.IsWindowsPlatform)
{
    browserControlInitParams = "--flag --option-with-value=value";
}
else if (PhotinoWindow.IsMacOsPlatform)
{
    browserControlInitParams = JsonSerializer.Serialize(new
    {
        flag = true,
        optionWithValue = "value"
    });
}
else if (PhotinoWindow.IsLinuxPlatform)
{
    browserControlInitParams = JsonSerializer.Serialize(new
    {
        flag = true,
        optionWithValue = "value"
    });
}

PhotinoWindow window = new PhotinoWindow()
    .SetTitle("Photino Testing")
    .SetBrowserControlInitParameters(browserControlInitParams)
    .LoadRawString("Hello World!");

window.WaitForClose();
```

**Comment by zxyao145** [comment]
@philippjbauer 

Hi, I am using it on the window, but this parameter does not seem to be taking effect. How should I use `SetBrowserControlInitParameters`?



```c#
string browserControlInitParams = string.Empty;

if (PhotinoWindow.IsWindowsPlatform)
{
    browserControlInitParams = "--flag --IsStatusBarEnabled=false";
}
return browserControlInitParams;
```

**Comment by zxyao145** [comment]
And when I upgrade to Photino.NET 2.5.0 (with Photino.Blazor 2.6.0)，the Width and Height configuration doesn't work

```c#
app.MainWindow
    .SetBrowserControlInitParameters(GetBrowserControlInitParameters())
    .SetWidth((int)(960 * 1.25))
    .SetHeight((int)(593 * 1.25));
```

**Comment by philippjbauer** [comment]
> @philippjbauer
> 
> Hi, This is great. And I am using it on the window, but this parameter does not seem to be taking effect. How should I use `SetBrowserControlInitParameters`?
> 
> ```cs
> string browserControlInitParams = string.Empty;
> 
> if (PhotinoWindow.IsWindowsPlatform)
> {
>     browserControlInitParams = "--flag --IsStatusBarEnabled=false";
> }
> return browserControlInitParams;
> ```

According to this https://superuser.com/a/1490951 you might be able to set `--kiosk` to turn it off. I. e. `browserControlInitParams = "--kiosk";`

**Comment by zxyao145** [comment]
> @zxyao145 You must also call .SetUseOsDefaultSize(false) For various reasons, we can't rely on just seeing that Height and Width have been set to override using the platform default. The same goes for setting the initial window location.

Thanks a lot, it works well!

**Comment by zxyao145** [comment]
@philippjbauer 
> According to this https://superuser.com/a/1490951 you might be able to set `--kiosk` to turn it off. I. e. `browserControlInitParams = "--kiosk";`

Hi, this is effective. Is this flag similar to the flag used during Chrome's running?

**Comment by philippjbauer** [comment]
@zxyao145 It's a Chromium flag from what I can tell. I cross checked with the link provided earlier (https://peter.sh/experiments/chromium-command-line-switches/)

**Comment by zxyao145** [comment]
> @zxyao145 It's a Chromium flag from what I can tell. I cross checked with the link provided earlier (https://peter.sh/experiments/chromium-command-line-switches/)

@philippjbauer Thanks a lot. By the way, Photino is a great project, thank you and all the other contributors!
