### ISSUE TITLE
Using Chrome webview (during development)

### ISSUE THREAD

**Issue by aabluedragon** [tryphotino/photino.NET#136]
Using Photino.Blazor, is it possible to force usage of chromium as webview? at least during development, as I'm more used to it, and I'm sure many other are too, especially those coming from Electron based development.

**Comment by philippjbauer** [comment]
Hi @aabluedragon, sorry but this would require re-implementing all native functionality that we expose through the API that the .NET package uses with Chromium specific implementation. Essentially a complete rewrite of the native library parts that touch the browser control.
