### ISSUE TITLE
empty window for `dotnet new photinoapp` on `Ubuntu 22.04.2 LTS`

### ISSUE THREAD

**Issue by BryanWilhite** [tryphotino/photino.NET#137]
i went through the normal `dotnet new photinoapp -o MyPhotinoApp\` into and am seeing this:

![image](https://user-images.githubusercontent.com/5226627/236656574-7f2f4898-3cf8-46eb-9ac8-9b80d409f9e9.png)

there is some `symbol lookup error`:

```console
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```

:octocat: source code: https://github.com/BryanWilhite/dotnet-core/tree/master/dotnet-photino

here is my environment:

```console
OS: Ubuntu 22.04.2 LTS x86_64 
Host: MINIPC PB50 0602 
Kernel: 5.19.0-41-generic 
Uptime: 7 hours, 52 mins 
Packages: 2669 (dpkg), 50 (snap) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
DE: GNOME 
WM: Mutter 
WM Theme: Yaru-dark 
Theme: Yaru-olive-dark [GTK2/3] 
Icons: Yaru-olive [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8) @ 2.300GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 7427MiB / 30019MiB 
```

```console
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.408 [/usr/share/dotnet/sdk]
  7.0.203 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by MikeYeager** [comment]
@BryanWilhite Would you mind right-clicking on the webview, opening Dev Tools and seeing if there are any errors shown in the console? Also open the Network tab in Dev Tools, refresh the page and see if there are any errors retrieving files. Thanks!

Also, it looks like installing VS Code via snap sometimes messes up the path to GTK. See if this post fixes it for you. https://stackoverflow.com/questions/75921414/java-symbol-lookup-error-snap-core20-current-lib-x86-64-linux-gnu-libpthread/75956168#75956168 

Historically, installing VS Code via snap didn't even work and it appears to still be problematic. We recommend downloading an installing it manually. There are instructions on the VS Code web site.

**Comment by BryanWilhite** [comment]
@MikeYeager there is no right-click context menu appearing here:

![image](https://github.com/tryphotino/photino.NET/assets/5226627/8732951e-d719-47f5-b2db-131622c29c1d)

But, yes, I have installed VSCode via snap. I had to uninstall my Obsidian snap because it caused `amdgpu` crashes that took down the whole desktop. So it makes sense to me that the VSCode snap would have/cause problems.

**Comment by BryanWilhite** [comment]
Sorry about the confusion @MikeYeager: Photino runs fine outside of the VSCode terminal:

![image](https://github.com/tryphotino/photino.NET/assets/5226627/db69e2a5-6469-4582-9284-c1aba5d02de3)

You already know that the VSCode terminal is an environment that is not same as my local desktop/terminal environment.
