### ISSUE TITLE
Hardware Acceleration / WPE Support

### ISSUE THREAD

**Issue by foltram** [tryphotino/photino.NET#138]
Does Photino support Hardware Acceleration or WPE? My use case relies on hardware acceleration and it seems (at least on Linux) the standard WebKit browser doesn't use it. From some research it appears that OS standard webkit browsers are pretty much only capable of using software rendering. [WPE](https://wpewebkit.org/) seems to be an embedded / native port of webkit that has hardware acceleration (amongst other things).

**Comment by ottodobretsberger** [comment]
Photino utilizes WebkitGTK on Linux, so I would say no.
