### ISSUE TITLE
Media autoPlay policy Required

### ISSUE THREAD

**Issue by hejiajun107** [tryphotino/photino.NET#142]
Since the webview disabled miedia autoplay by default,need some option to enabled this wihout user gesture.
Like the comandline args in chrome --autoplay-policy=no-user-gesture-required or like android webview  option mediaPlaybackRequiresUserGesture

**Comment by philippjbauer** [comment]
Hi @hejiajun107!

We added a way to pass init flags to the browser control in Photino.NET v2.5.0 (just released). You can try to pass `--autoplay-policy=no-user-gesture-required` as a string via the SetBrowserControlInitParameters method.

```cs
PhotinoWindow window = new()
    .SetBrowserControlInitParameters("--autoplay-policy=no-user-gesture-required")
    // ... other options
    .Load(...);
```

Please let us know if this resolves your issue!

**Comment by hejiajun107** [comment]
It works

**Comment by philippjbauer** [comment]
Thank you for confirming this @hejiajun107!
