### ISSUE TITLE
New window to load blazor page

### ISSUE THREAD

**Issue by charleypeng** [tryphotino/photino.NET#144]
As i found the new version of photino supports open new window feature and it really can open and load .html file in a new window, this is great! Any idea on open razor page in a new window? Many thanks!

**Comment by philippjbauer** [comment]
If you have an ASP.NET server running in the background you should be able to load the URL that corresponds to the page you want to load? Just like you would access it in the address bar of your browser ...

You can take a look at the StaticFileServer example in the Photino.Sample repo to get an idea on how to start a server with the Photino application. This server is not configured to serve razor pages and needs to be extended to include that functionality and routing to your pages just like any other ASP.NET razor server.

**Comment by charleypeng** [comment]
> If you have an ASP.NET server running in the background you should be able to load the URL that corresponds to the page you want to load? Just like you would access it in the address bar of your browser ...
> 
> 
> 
> You can take a look at the StaticFileServer example in the Photino.Sample repo to get an idea on how to start a server with the Photino application. This server is not configured to serve razor pages and needs to be extended to include that functionality and routing to your pages just like any other ASP.NET razor server.

Thanks. I have found a way by wraping in a photono window.
