### ISSUE TITLE
Use Vite instead of create-react-app/react-scripts

### ISSUE THREAD

**Issue by stevesobol** [tryphotino/photino.NET#145]
Hello,

Since CRA is not maintained anymore, from what I can tell, and Vite's significantly faster anyhow, I'm trying to get a simple Photino app to build with Vite instead. 

I have it almost working with Jetbrains' Rider. Not so much with VS 2022... Intellisense tells me there are a bunch of errors.

I'm not asking anyone else to work on this; I am working on it on my own. I'm opening an issue to document that I'm doing it. Eventually I'll get my code working and polished, and I'll open a pull request... I'm not sure whether we'd want to update the React VS template, or create a new one.

**Comment by stevesobol** [comment]
Incidentally, @MikeYeager , I don't know about the other frameworks, but the React skeleton has a serious problem.

Making an API call before displaying any UI is a _very_ bad idea. It gives the impression that Photino is extremely slow to start up.

**Comment by rtmann** [comment]
I got it working in Rider, VS2022, and VSCode with Vite.  But I rolled it from scratch, I manually made a vite project etc and manually set up all the configs.

**Comment by stevesobol** [comment]
What we need is a template. Do you have your work sitting in a repo somewhere? I'd like to take a look at it.

**Comment by Jesse-Lucas1996** [comment]
Can we see an example of this working? I'm doing the same thing but photino is not serving up the index.html page

**Comment by philippjbauer** [comment]
The newest samples (Photino 3.0 release) adhere to the latest way of initializing the three JS frameworks as per each of their install docs.
