### ISSUE TITLE
Smooth scrolling?

### ISSUE THREAD

**Issue by Nicks182** [tryphotino/photino.NET#148]
Hi

I've been experimenting with using HTML as my GUI for desktop apps. Recently I used the WebView2 control in a WPF app to load an embedded html page in the app's main window and then also include Kestrel web server in the app to host the page so I can access it over the local network.

With WebView2 I was able to set the flag to enable smooth scrolling which makes the UI feel so much nicer and modern. The main issue with this approach is the application size. My app ended up being 213Mb :(

So I'm now currently just messing around/experimenting/figuring things out with Photino, but so far I can't see a way to get smooth scrolling to work... maybe I'm just being an idiot which is quite possible ;) 

Setting the scroll-behavior in CSS seems to make no difference.

Is it possible to enable smooth scrolling for my HTML in photino?

**Comment by philippjbauer** [comment]
We added a way to pass init flags to the browser control in Photino.NET v2.5.0 (just released). You can try to pass `--enable-smooth-scrolling` as a string via the `SetBrowserControlInitParameters` method.

```cs
PhotinoWindow window = new()
    .SetBrowserControlInitParameters("--enable-smooth-scrolling")
    // ... other options
    .Load(...);
```

I found this flag here (https://peter.sh/experiments/chromium-command-line-switches/). From my understanding, WebView2 uses Chromium and these flags should apply to WebView2.

**Comment by Nicks182** [comment]
Sweet! Just tried it and it's working.

`if (PhotinoWindow.IsWindowsPlatform)
{
    // Windows specific initialization parameters
    browserControlInitParams = "--enable-smooth-scrolling";
}`

I know it's such a simple thing, but IMO it makes such a big difference for UX.

Now to go through what's new in Photino 2.5 :)

**Comment by philippjbauer** [comment]
Awesome! Thank you for the response Nick! :)
