### ISSUE TITLE
[MacOS] Photino's never exits upon closing window

### ISSUE THREAD

**Issue by gerwim** [tryphotino/photino.NET#149]
When running Photino on MacOS, upon closing the window (or even the whole application using CMD+Q), the underlying process is not killed.

To reproduce:

1. Clone the samples repository (https://github.com/tryphotino/photino.Samples)
2. Run any project, e.g. `Photino.HelloPhotino.NET`
3. Start the application
4. Kill the foreground application
5. Observe the debugger is still active and the code is still in the `window.WaitForClose();` loop
6. Kill the running `dotnet` process to actually kill the application

**Comment by philippjbauer** [comment]
Good catch! Not easy to find when VS Code is running that spawns dotnet processes of its own.

**Comment by philippjbauer** [comment]
@gerwim This has been rectified in the latest release v2.5.2 (https://github.com/tryphotino/photino.NET/releases/tag/v2.5.2)
