### ISSUE TITLE
kylin v10 arm64 unable to load shared library 'photino.native'

### ISSUE THREAD

**Issue by tkggusraqk** [tryphotino/photino.NET#153]
error：unable to load shared library 'photino.native'
![kylinv10-arm64](https://github.com/tryphotino/photino.NET/assets/5164663/0ba64ad2-0a80-427b-a36e-9e89d0908011)

**Comment by MikeYeager** [comment]
@tkggusraqk We don't have a configuration to test this on. You may need to compile Photino.Native on your distro.

**Comment by tkggusraqk** [comment]
Unfortunately, it seems that it does not support arm64 very well, so if you want to use it as an alternative to electron, there is still a long way to go.
