### ISSUE TITLE
Photino blazor template

### ISSUE THREAD

**Issue by josago97** [tryphotino/photino.NET#155]
Hello, would it be possible to add a Visual Studio Community template to create applications with photino and Blazor? Thank you

**Comment by MikeYeager** [comment]
We do have a set of VS project templates for all of our samples EXCEPT Blazor as well as project templates you can use from the dotnet CLI. They are currently a little out of date (it's on our list), but you can update the NuGet references manually. The VS templates can be found here https://github.com/tryphotino/PhotinoSamples.VSExtension and the CLI templates here https://github.com/tryphotino/PhotinoSamples.VSCodeTemplates. For Blazor, we recommend copying the Sample app from the Photino.Blazor repo https://github.com/tryphotino/photino.Blazor (download the repo as a .zip file) to a local folder. We are considering adding better support for Blazor now that Microsoft has made some advancements with .NET8 and that would include adding the Blazor sample to the other samples and creating a project template for it.

**Comment by josago97** [comment]
Yes please, although you can now download the example project and modify it, a template for VS would be much more convenient. Thank you.

**Comment by josago97** [comment]
> We do have a set of VS project templates for all of our samples EXCEPT Blazor as well as project templates you can use from the dotnet CLI. They are currently a little out of date (it's on our list), but you can update the NuGet references manually. The VS templates can be found here https://github.com/tryphotino/PhotinoSamples.VSExtension and the CLI templates here https://github.com/tryphotino/PhotinoSamples.VSCodeTemplates. For Blazor, we recommend copying the Sample app from the Photino.Blazor repo https://github.com/tryphotino/photino.Blazor (download the repo as a .zip file) to a local folder. We are considering adding better support for Blazor now that Microsoft has made some advancements with .NET8 and that would include adding the Blazor sample to the other samples and creating a project template for it.

I would like to help add a template to create projects with Blazor, however, I have entered both repositories that you indicated but it turns out that they no longer exist.

**Comment by ottodobretsberger** [comment]
@josago97 the repository visibility was private. I have changed it to public and you should be able to see those repos now.

**Comment by josago97** [comment]
I have created a [PR](https://github.com/tryphotino/PhotinoSamples.VSExtension/pull/6) to add a template for Blazor in the .NET 8 version for Visual Studio, so that you can review it and, if appropriate, include it.
