### ISSUE TITLE
SetMaximized only works after Window is Created. This intended?

### ISSUE THREAD

**Issue by Nicks182** [tryphotino/photino.NET#158]
Hi

Ever since I started messing around with Photino I've never been able to set my window to be Maximized during window setup. I have to use the 'WindowCreated' event and then set the Window to be maximized. Using the 'WindowCreating' event does not work either.

This is on Windows... not sure if Mac or Linux is the same.
My project is .NET 8.0 with Photino.NET 2.5.2, but I tried it in 7.0 with the same results.

Below is a screenshot of a simple test and it only works with the Created event. I feel like I must be doing something wrong... or is this how it's intended to be set/used??

![image](https://github.com/tryphotino/photino.NET/assets/13113785/43649cb8-b8d5-47b3-86ac-292f2b0e3b29)

Regards
Nick

**Comment by MikeYeager** [comment]
@Nicks182 Thank you for this bug report. We found and fixed the issue. It will be in the next release (the one with .net 8 support).
