### ISSUE TITLE
Input select display not located correctly

### ISSUE THREAD

**Issue by josago97** [tryphotino/photino.NET#161]
When you create an InputSelect element, hit display and move the window, the displayed menu does not move with the window. The expected behavior would be either the dropdown closes because you are moving the window and therefore losing focus, or the menu moves next to the window.
The following example is made with Blazor.
![image](https://github.com/tryphotino/photino.NET/assets/26380095/fdb40ecb-3ab0-47cf-af95-72c7e193dc9d)

**Comment by MikeYeager** [comment]
@josago97 This appears to be an open issue with the WebView2 control, not with Photino. See this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/780

When tested on MacOS, the popup closes if you move the window.

**Comment by josago97** [comment]
I have put an [issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4324) in the WebView repository about this problem. They have answered me that you have to use the following API [NotifyParentWindowPositionChanged](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2host?view=webview2-0.9.430#notifyparentwindowpositionchanged).
Does Photino use such API to notify window movement?

**Comment by ottodobretsberger** [comment]
Thank you for linking this issue from WebView. That is interesting to hear. I was not aware of this requirement, but we will take another look on whether this needs to be done in Photino and if so, incorporate that.

**Comment by josago97** [comment]
Okay, thank you very much for your work and reporting.

**Comment by philippjbauer** [comment]
Closing this issue as it is not an issue of Photino but of WebView in Windows. See issue on their repo above.
