### ISSUE TITLE
System Tray For All OS

### ISSUE THREAD

**Issue by oceanworldzebra** [tryphotino/photino.NET#171]
When close the windows, the application will be quit.

Want:
      Close the windows, hide from taskbar. Using system tray menu to show the window again.

**Comment by domialex** [comment]
I'm pretty sure you can create a console program with a tray icon/menu that would create the windows when necessary.

Without a main program running somewhere, the program will simply close. So the windows would be the children of the console program.

**Comment by philippjbauer** [comment]
This is not in scope for Photino. Please search on how to use the system tray in windows with a dotnet console application.
