### ISSUE TITLE
Photino window is completely blank when the entrypoint (i.e. Main) method is defined as an async method that returns a 'Task' object

### ISSUE THREAD

**Issue by Arc8ne** [tryphotino/photino.NET#180]
When the 'Program.Main' method (i.e. the entrypoint method) is defined as an async method that returns a ``Task`` object, the opened Photino window is completely blank (i.e. completely white) with no HTML being rendered to it despite waiting for a long time.

**Comment by philippjbauer** [comment]
Another user seems to have found a way to get the "async Main scenario" working. See https://github.com/tryphotino/photino.NET/issues/52#issuecomment-2074325176

Please let us know if it works for you as well

**Comment by Arc8ne** [comment]
Hi, thanks for the response and for the linked workaround, however, I have already found and made use of a different method to get the said scenario working, the said method was found in this StackOverflow answer: https://stackoverflow.com/a/9212343 and seems to be working for my current use case.
