### ISSUE TITLE
v3.0.14 does not have the Inspect option on the context menu

### ISSUE THREAD

**Issue by microhobby** [tryphotino/photino.NET#190]
I'm trying to migrate to the latest version, but even adding the:

```csharp
.SetDevToolsEnabled(true)
.SetContextMenuEnabled(true)
```

the context menu does not show the Inspect option that the v2.6.0 have.

**Comment by philippjbauer** [comment]
Hi @microhobby,

which OS are you using? We're not seeing this on Linux, Windows and macOS behave as expected.

**Comment by microhobby** [comment]
Hey @philippjbauer 

is a Debian 12 under WSL 2. v2.6.0 works ok, I made the changes to work with the v3.0.14 but was unsuccessful. Also, I created a new fresh project to make sure that was nothing on the old application, follow the attached:
[photino.zip](https://github.com/user-attachments/files/15917307/photino.zip)

**Comment by LauraWebdev** [comment]
I have been experiencing the same issue on Fedora 40 when updating from Photino.NET 2 to 3

**Comment by redplane** [comment]
Same here.
The inspect option is available on MacOS but does not appear in `Ubuntu 22.04`:
![Screenshot from 2024-09-28 20-32-26](https://github.com/user-attachments/assets/86a62ecd-9816-4f2f-95dd-54aa513f2dba)
