### ISSUE TITLE
find a bug

### ISSUE THREAD

**Issue by Jaffoo** [tryphotino/photino.NET#191]
At first I put my own project on the server to run, then shut down mstsc, and the next time I used mstsc to connect, the program would crash, I thought it was my code. So I download the code sample, compile it and test it on the server, and the same problem still occurs.
How to solve this problem?

**version info:**
WebView2 is the latest version as of 2024
Others are shown in the figure
![image](https://github.com/tryphotino/photino.NET/assets/86825947/2558d96a-aa07-44ee-959b-d026e5be747e)
![image](https://github.com/tryphotino/photino.NET/assets/86825947/b4bbb927-355c-4c87-9f1c-eb9afc777d0f)

**Comment by philippjbauer** [comment]
Hi @Jaffoo,

can you please tell us what version of Windows you are using on the host system and if this also happens when you try to run a Photino application on your local system.

Thank you

**Comment by Jaffoo** [comment]
> 嗨，
> 
> 您能否告诉我们您在主机系统上使用的 Windows 版本，以及当您尝试在本地系统上运行 Photino 应用程序时是否也会发生这种情况。
> 
> 谢谢

The system used by the server is Windows-2016-Datacenter-cn.
This problem only occurs with remote connections (mstsc). 
Procedure: 1. Run the software on the remote server. 2. Disconnect the remote service. 3. Log in to the remote service again and this problem occurs. 
If I was using it on my own computer, or more precisely do not use the remote desktop to control the computer, it will not appear.

**Comment by philippjbauer** [comment]
@Jaffoo We tried to replicate this problem on a Windows 11 virtual machine, but we're unable to do so. This may be a driver failure of some sort but it's hard to determine with all the different moving pieces involved in this particular situation. Sorry that we can't be of more help.
