### ISSUE TITLE
Does Photino.NET support .NET MVC projects?

### ISSUE THREAD

**Issue by LapinskasL** [tryphotino/photino.NET#195]
I want to be able to integrate Photino.NET into a .NET MVC project. Is this possible? I'm unable to find a guide on how to do this.

**Comment by CypherPotato** [comment]
It should be compatible with any web framework. Did you even tried to set the `PhotinoWindow.StartUrl` to your .NET MVC app? Maybe you can host an PhotinoWindow within your .NET MVC app.

**Comment by MikeYeager** [comment]
@LapinskasL There is a Photino.Server example that demonstrates hosting an ASP.NET server. You should have no trouble hosting an MVC app that way. The ASP.NET server comes virtually free since we're already running the full .NET runtime. Closing, but please re-open if you run into issues.
