### ISSUE TITLE
How Photino invokes an WebView wrapper?

### ISSUE THREAD

**Issue by CypherPotato** [tryphotino/photino.NET#196]
From what I've seen, at least on Windows 10 and 11, Photino runs on top of the Microsoft Edge WebView, but I can't control which version of the WebView it will use, nor do I know which webview it uses on other operating systems.

Different WebViews can bring notable changes to web resources, which complicates development and removes the concept of "portability".

So, I want to know: how does Photino select which webview engine to use on different operating systems and how can I change this to use a specific engine for all operating systems, like Chromium v.120 for example?

**Comment by MikeYeager** [comment]
@CypherPotato Please refer to the docs at https://www.tryphotino.io/

`Photino.Native is a C++ (and Objective-C) wrapper around the OS’s built-in Chromium or WebKit-based browser control in it. On Windows it uses the Chromium Edge based WebView2 control, on macOS it uses Safari’s WKWebView and on Linux it uses WebKitGTK+ 2. The Photino.Native package is compiled for each platform and distributed via NuGet.`

You can control the version of WebView2 on Windows platform (again, see the docs). If you are looking to use Chromium across all platforms, take a look at Electron as it distributes the Chromium runtime as part of every installation. Photino does not take that approach.
