### ISSUE TITLE
.NET Templates still don't reference photino v3.x

### ISSUE THREAD

**Issue by raddevus** [tryphotino/photino.NET#199]
The .NET project templates still reference the Photino v2.x versions. 

I just set up a new box to do development (installed .NET 8.x) and then installed the photino .NET project templates (as instructed at [https://www.tryphotino.io/](t https://www.tryphotino.io/).

I created a new photino .net project: `dotnet new photinoapp -o MyPhotinoApp`

That project references photino 2.3.0 in the csproj:

`<PackageReference Include="Photino.NET" Version="2.3.0" />`

I want to use the latest version so I had to go out to Nuget and find the 3.x versions and update my project.

**Comment by MikeYeager** [comment]
@raddevus We've had a wave of business travel and vacations recently and are working on getting caught up. We will get these out as soon as we have the hours to spend. Cheers.
