### ISSUE TITLE
Start maximized (not fullscreen)

### ISSUE THREAD

**Issue by peerem** [tryphotino/photino.NET#20]
We want to start a Blazor app maximized. Unfortunately there is no possibility to do this in the Constructor of the PhotinoWindow or in ComponentsDesktop.Run, similar to the WindowState in Windows Forms.

**Comment by MikeYeager** [comment]
This requires a change to photino.Native and is covered there.
https://github.com/tryphotino/photino.Native/issues/28 
https://github.com/tryphotino/photino.Native/issues/35
https://github.com/tryphotino/photino.Native/issues/36
