### ISSUE TITLE
Which verison of Photino.Native support libstdc++.so.6.0.25?

### ISSUE THREAD

**Issue by towerbit** [tryphotino/photino.NET#200]
I tried the rencently Photino v3.0.14, but it requited  the libstdc++.so 6.0.30 which is not avalible on deepin linux 20.9(debian 10) with only libstdc++.so.6.0.25. How can I figure out which verison of Photino.Native.so fit it?

**Comment by towerbit** [comment]
OK, here is the answer, Photino.NET v2.1.11 as the last version  works fine with libstdc++.so v6.0.25 which depends on Photino.Native v2.1.4 .

**Comment by MikeYeager** [comment]
@towerbit Yes, so many Linux versions make difficult to support. Please have a look at the docs https://github.com/tryphotino/photino.Samples/tree/master/Photino.PublishPhotino/PublishPhotino if you want to use the newer versions with newer dependencies.
