### ISSUE TITLE
Unable to navigate (load or loadrawstring) after WaitForClose() on Linux for v3 and above - passes only one char

### ISSUE THREAD

**Issue by electricplane** [tryphotino/photino.NET#203]
Brand new to Photino and loving it BTW ...

For version 3, and above, attempts to call load or loadrawstring after it is originally set and you call WaitForClose() appear to be only passing the first character of the string, but only for linux.  Works like a champion on Windows.

Example would be calling loadrawstring("AAAAA") gives you just "A" in the browser.  Calling load with a URL gives you a "can't display URL".

Works just fine on 2.6 ... no issues.

**Comment by electricplane** [comment]
My goodness, sorry for leaving that out in the first place.  3.1.14 was what I was using, but also tried it against 3.0.14.  Whatever I can do to help, I am there.

**Comment by MikeYeager** [comment]
We have identified the issue and are working to resolve it.

**Comment by electricplane** [comment]
Awesome - let me know if I can help with anything.

**Comment by philippjbauer** [comment]
Hi @electricplane, this was fixed the latest release 3.1.18
