### ISSUE TITLE
Open DevTools

### ISSUE THREAD

**Issue by Jaffoo** [tryphotino/photino.NET#207]
How can i open DevTools without using 'F12' key or mouse right click.
I mean, use the code to open the devtools directly, such as ```PhotinoWindow.OpenDevTools () ```

**Comment by MikeYeager** [comment]
Hello @Jaffoo As far as I know, there is no way to do it. Dev tools are implemented in each of the 3 browser controls (1 for each platform). We can pass settings to the controls to enable or disable the feature, but I don't believe there is a way to have the control pop up the dev tools other than with user interaction.

**Comment by domialex** [comment]
@MikeYeager It seems we can for both [libwebkit2gtk](https://webkitgtk.org/reference/webkit2gtk/stable/class.WebInspector.html) and [webview2](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.3240.44#opendevtoolswindow). My knowledge is limited in this, but it does seem supported.

**Comment by domialex** [comment]
@MikeYeager I also noticed that webkit2gtk has no hotkeys to open the devtools (unless we enable context menu, but not every distro has the option to inspect), therefore we need a way to open them programmatically. I think this issue should be re-opened.
