### ISSUE TITLE
PhotinoWindow does not show characters properly in Title

### ISSUE THREAD

**Issue by hejiajun107** [tryphotino/photino.NET#215]
PhotinoWindow does not show characters properly in Title when use Chinese characters,
But it works well in previous version
```
      app.MainWindow
          .SetIconFile("favicon.ico")
          .SetTitle("测试");
```
![image](https://github.com/user-attachments/assets/644ebf46-9720-469b-86f4-835c4a433ef9)

**Comment by MikeYeager** [comment]
@hejiajun107 Thanks for finding that. Apparently, it's only a problem on Windows. We found and fixed the issue and it will be in the next release.
