### ISSUE TITLE
Load the url again

### ISSUE THREAD

**Issue by Jaffoo** [tryphotino/photino.NET#225]
As shown in the figure, I can't load the page twice, is this writing not supported?
![template](https://github.com/user-attachments/assets/57f176c5-b9d4-4de2-9eb1-4979463228dd)

**Comment by Jaffoo** [comment]
> As shown in the figure, I can't load the page twice, is this writing not supported? ![template](https://private-user-images.githubusercontent.com/86825947/386132434-57f176c5-b9d4-4de2-9eb1-4979463228dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1Nzc5MzYsIm5iZiI6MTczMTU3NzYzNiwicGF0aCI6Ii84NjgyNTk0Ny8zODYxMzI0MzQtNTdmMTc2YzUtYjlkNC00ZGUyLTllYjEtNDk3OTQ2MzIyOGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA5NDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMzI2YTcxOTkxZGYwODYzODAzNTE4OTA5YzIwMTkzMDFiODczM2QxOTA1ZDA3NzE5N2E2MmFjNzg1ZDhmMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I0Ix5eKeY7fkt8QFQ1ff8yLhjTESP4ATlr2Jo01oCgQ)

In my practice, I found that when Photino.NET version is greater than 3.1.16 and Photino.Native version is greater than 3.1.15, this method is not valid.

**Comment by MikeYeager** [comment]
@Jaffoo This is fixed in the next version. Thanks for finding it. It's related to the string translation changes that were made.
