### ISSUE TITLE
SetIconFile doesn't work in any photino version on mac or linux

### ISSUE THREAD

**Issue by raddevus** [tryphotino/photino.NET#228]
I have tried numerous versions of `SetIconFile()` on 

1. Linux (Ubuntu 24.04) running Photino.Net version 2.6.0
2. macOS - running Photion.Net version 2.3.2 & 3.2.3

I've tried all manner of file types for the icon (.ico, .icns, .png).

I never see the icon show up on the task bar or on the app.

I see the default blank white icon or the black icon with EXE in the background.

I am calling SetIconFile() in the initialization of the main window (in the template code):

```
var window = new PhotinoWindow()
                .SetTitle(windowTitle)
                .SetIconFile(@"wwwroot/icon.ico")
```

The ico files I'm using is an actual icon files (.ico, .icns, png) used in other projects successfully so I don't believe that is the problem.

I also know that `SetIconFile()` does seem to be making  a successful call because if I give it a path to a non-existent file then I get an error that the file doesn't exist.

**Comment by MikeYeager** [comment]
@raddevus SetIconFile() sets the icon to display on the window title bar, so it only works on Windows. Linux and Mac don't show icons on the window title bar. Icons can be set for the application, start menu, etc., however these features use a different mechanism. See [publish guide in samples](https://github.com/tryphotino/photino.Samples/blob/master/Photino.PublishPhotino/PublishPhotino/README.md)
