### ISSUE TITLE
Allow using Chromium in all platforms

### ISSUE THREAD

**Issue by CypherPotato** [tryphotino/photino.NET#229]
The Photino project is certainly a great achievement for the .NET community and a great alternative to Electron and Tauri. The problem I see with Photino is developing an application to be supported by a browser that I have no control over. I don't know which browser will be used, each platform has its own wrapper and version for each one. In this case, it is a bit difficult to track where the code is executed.

I would like to know if there is a way, or if there is a way, to make Photino run only CEF (Chromium) on all platforms. Maybe download the CEF runtime the first run or embed it in the final package, I don't know how it would be.

Is this feasible for the project?

**Comment by flyingpie** [comment]
@CypherPotato Why wouldn't you use actual CEF if you want CEF?

**Comment by CypherPotato** [comment]
@flyingpie I don't know of a simple, cross-platform solution like Photino, but Chromium for C#. I know of CefSharp, but it's limited to Windows only.

**Comment by flyingpie** [comment]
@CypherPotato Gotcha! What about Electron.Net or CefGlue?
- https://github.com/ElectronNET/Electron.NET
- https://github.com/OutSystems/CefGlue

**Comment by CypherPotato** [comment]
Didn't know about CefGlue. Also, i've heard some negative feedback about Electron.NET.

Thank you btw.
