### ISSUE TITLE
Error in Photino.Blazor example project when updating package

### ISSUE THREAD

**Issue by DavidMcGaha** [tryphotino/photino.NET#24]
When I update the nuget package, I get an error. Text:CS0234	The type or namespace name 'PhotinoNET' does not exist in the namespace 'PhotinoNET' (are you missing an assembly reference?)

When I go into the WindowProp.razor page and try to change it away from PhotinoNET.PhotinoNET to PhotinoNET.IPhotinoWindow or PhotinoWindow, I get an error saying that Topmost property is missing.

Attached image of files updated in the nuget update
![image](https://user-images.githubusercontent.com/54552493/110867492-6ff08c80-828c-11eb-9611-17c31a703f51.png)

**Comment by philippjbauer** [comment]
Hello @DavidMcGaha!

Thank you for your feedback! First off, there is a new version of the VS Extensions available since today. Go ahead and update to get the version that can utilize the new Photino package versions. That will take care of the missing `Topmost` property, it changed to `IsOnTop` in v1.1.x.

Also make sure that the namespace in the `_Imports.razor` file are correct for your project. When you create a new project from the template, VS is not replacing the `@using` statement to match the name you chose when creating the project.

```razor
// ./_Imports.razor
@using System.Net.Http
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.JSInterop

@* Replace HelloPhotino.Blazor with namespace from Program.cs *@
@using HelloPhotino.Blazor
@using HelloPhotino.Blazor.Shared
```

**Comment by DavidMcGaha** [comment]
Awesome. Thank you sir.

**Comment by DavidMcGaha** [comment]
Hi Philipp,

So, I had everything working on Windows and Linux(quite well I might add)
using the 1.0.7 version of the HelloPhotino.Blazor template. I upgraded to
1.1.1 and changed as described. The Linux version would no longer run.
.getting error:

File "app://app/" could not be found.

Downgrading back to 1.0.7 did not reverse the problem...so...

Then I reinstalled the extension and created a new app with the new
templates, changed  the _import file and I get a build error message that I
cannot seem to get past...
Severity Code Description Project File Line Suppression State
Error CS0246 The type or namespace name 'MainLayout' could not be found
(are you missing a using directive or an assembly reference?) OrderEntry1
C:\Users\dmcgaha\source\repos\OrderEntry1\OrderEntry1\App.razor 3 Active

Any ideas?

**Comment by DavidMcGaha** [comment]
When I downgrade the original working app to 1.0.7, I get this error on starting the Linux version 
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'Photino_SendMessage' in shared library 'Photino.Native'.
   at PhotinoNET.PhotinoNET.Photino_SendMessage(IntPtr instance, String message)
   at PhotinoNET.PhotinoNET.SendMessage(String message)
   at Photino.Blazor.IPC.<>c__DisplayClass3_0.<Send>b__0()
Aborted (core dumped)
