### ISSUE TITLE
Version of Photino.NET for .NET Framework

### ISSUE THREAD

**Issue by marcosqlbi** [tryphotino/photino.NET#27]
I am evaluating how to use Photino.NET in a .NET Framework application (in WPF). 
Creating a separate window would work well, I already tested using the message loop in WPF (with .NET 5) and it works.
The issue for .NET Framework is that Photino.NET is compiled for .NET Standard 2.1 - if it was .NET Standard 2.0 it would have worked, but there is a dependency on Marshal.GetHINSTANCE that is not available in .NET Standard 2.0.

Do you already evaluated if there could be a workaround? 
The alternative seems to create a .NET Framework version of Photino.NET. If I go that route, would it be possible to keep a single version of the source code with conditional directives, or do you think it would be better to create a separate project?

Any idea and comment would be appreciated - thanks!

**Comment by MikeYeager** [comment]
We're not sure there are many scenarios that make sense for Photino in WPF. That would limit it to the Windows platform, and WPF already has a wrapper for the WebView2 control. Also, at this point the full framework is becoming legacy. Photino would theoretically work in .NET 5 WPF, although again, we can't envision a scenario for it.

**Comment by marcosqlbi** [comment]
The scenario is adding a visualization feature to https://github.com/sql-bi/VertiPaq-Analyzer that can be used by existing applications that consume that library and are written in WPF or Windows Forms (using .NET Framework).
However, I understand the plan and I will evaluate creating a .NET Framework porting just to support the requirement we'll have in our library.
Thanks!
