### ISSUE TITLE
Self-contained Single File

### ISSUE THREAD

**Issue by kevinjpetersen** [tryphotino/photino.NET#34]
Since .NET 5 and .NET 6 still doesn't have a fully self-contained single file yet (while .NET Core 3.0/3.1 does) would you consider making Photino work with .NET Core 3.0/3.1 also so people has the option to get a fully self-contained single file application?

Or is there other plans for this?

**Comment by ottodobretsberger** [comment]
There are no plans to migrate Photino back to Core 3, and while we haven't actually tried and/or tested single file deployment in .NET 5 ourselves yet, it appears -according to MS documentation- that the single file application features from 3.0 have been enhanced in .NET 5 and should still be available:

https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file

**Comment by kevinjpetersen** [comment]
@ottodobretsberger While .NET 5/6 does have Single File deployment, they're not a true Single File as it still requires a few other files which are built together with it, to run.

While .NET Core 3.0/3.1 is a single file only.

**Comment by ottodobretsberger** [comment]
We do not consider backward compatibility to 3.0 or 3.1 at this point. The overhead in changes would be too much to efficiently keep up with.
There are planned changes for .NET5/6 in that regard though, so we're hopeful to see true single file deployment again.
