### ISSUE TITLE
Unable to debug window inside of Rider

### ISSUE THREAD

**Issue by drewkill32** [tryphotino/photino.NET#38]
When I am using JetBrains Rider to debug my Photino app I an error. I don't get the error when running in Visual Studio. 

```text
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

I suspect that it is something to do with the [Photino.Native](https://github.com/tryphotino/photino.Native) part of the app. Should this question be posted there?

**Comment by ottodobretsberger** [comment]
Usually this error is an indication of a missing WebView installation. Maybe Rider doesn't have access to it? Have you tried running Rider in Admin mode? Since it does run in VS, the requirements seem to all be met and an issue to access them persists for Rider.

**Comment by drewkill32** [comment]
Progress. I tried running as admin and get the following error. Is there a way to change the path the WebView is looking at? Or is the process that Rider is using that needs access to that directory?

![image](https://user-images.githubusercontent.com/19336434/113330052-53280180-92ec-11eb-921d-e91f114b7d73.png)

**Comment by MikeYeager** [comment]
@drewkill32 This is an unrelated issue that has to do with installing into the Program Files folder. It is slated for development asap. See https://github.com/tryphotino/photino.Native/issues/58 for details.
