### ISSUE TITLE
Blank index page on macOS Big Sur

### ISSUE THREAD

**Issue by CiaronHowell** [tryphotino/photino.NET#39]
Hi,

I've been getting a blank index page from the sample projects as shown in the picture below.
![image](https://user-images.githubusercontent.com/8986930/112723093-cbfe1680-8f04-11eb-94d0-fc0d66b1dfab.png)

I've checked that the index.html file does exist and that the program can see it. I've also tried using a link to a website to see if that would load instead.

I assume this could be an issue only on my machine but I can't seem to pinpoint what could cause this issue. Especially when I'm not getting any errors except one about the Touchbar: `2021-03-27 14:00:18.592 dotnet[43611:2198090] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fe9d97180f0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.`

Any help would be appreciated.

**Comment by sanme98** [comment]
Hi @CiaronHowell, did u found the solution for this issue?

**Comment by CiaronHowell** [comment]
Hi @sanme98, it was for my dissertation for University so it was a while ago but I think there was an issue with my HTML so it wouldn't load the page
