### ISSUE TITLE
Static files from nugets

### ISSUE THREAD

**Issue by ArieBen** [tryphotino/photino.NET#40]
I'm trying to reference
`<script src="_content/Telerik.UI.for.Blazor/js/telerik-blazor.js" defer></script>`
or
`<link rel="stylesheet" href="_content/Telerik.UI.for.Blazor/css/kendo-theme-default/all.css" />`
But it's not found.

Edit:
I've published the solution to a folder check where the files go. The _content folder was actually created on deploy and the references work. The folder isn't created during the debug build though....

**Comment by ottodobretsberger** [comment]
In the properties, have you made sure the setting "Copy to Output Directory" is set to "copy if newer" on those files you're referencing?

**Comment by ArieBen** [comment]
these are embedded files in the Telerik.UI.for.Blazor package.
The _content folder is created in a publish to folder so I guess the build action must be good, there's no issue with the package. But I had to copy that _content folder to the bin/debug manually to be able to use these components in debug mode.
