### ISSUE TITLE
Window buttons are on the left side on Ubuntu 20.10 (Wayland)

### ISSUE THREAD

**Issue by zeroskyx** [tryphotino/photino.NET#45]
Greetings,

using the sample app "HelloPhotino.NET" (or any other bare-bones configuration) on Ubuntu 20.10 using Wayland and .NET 5.0.5 (SDK 5.0.202), the window buttons are placed on the left side of the titlebar instead of the right side:

![image](https://user-images.githubusercontent.com/7782966/116381800-855a4f80-a815-11eb-9550-8e5663db8431.png)

Is there a way to configure this setting?

EDIT: the issue only occurs on Wayland, on X11 the buttons are placed correctly.

Thanks in advance!

**Comment by MikeYeager** [comment]
@zeroskyx Wow, have not seen that before. I haven't used Wayland. I'll take a look and see what I can find.

**Comment by ottodobretsberger** [comment]
There should be utilities that allow you to tweak the UI for Wayland to place the controls as you please.
This doesn't appear to be related to Photino though.
