### ISSUE TITLE
Photino Samples not finding WebView2 component

### ISSUE THREAD

**Issue by bouscarlo** [tryphotino/photino.NET#46]
While trying to run the samples, it seems the application tries to run the MicrosoftEdgeWebview2Setup.exe file (to update or get the latest WebView2 components). Unfortunately, I have a company GPO that does not allow Edge to be updated.

Isnt there a way to use the existing msedge WebView component or list the existing WebView components to see if they require an update?

Thanks,
--
John

**Comment by MikeYeager** [comment]
@bouscarlo Photino relies on the evergreen installation of the Chromium Edge WebView control. Unfortunately, we can't support the older, non-chromium version of Edge or early version of the chromium based Edge as there is no WebView control for them. The evergreen version allows security updates as well as supporting new features in Photino as they become available in the control itself.
