### ISSUE TITLE
Zoom property

### ISSUE THREAD

**Issue by ncpunt** [tryphotino/photino.NET#47]
Just installed Photino for a test run and I love it (especially the small footprint).
However, I sometimes build scalable UI's, in which the zoom state is connected to the window size.
A zoom property is present in most other web window implementations (e.g. CefSharp),
but it seems to be missing in Photino.NET. I know it is there in Edge.WebView2, it just needs to be exposed.

**Comment by MikeYeager** [comment]
We're hoping to get a V2 out soon if our day jobs permit and we'll try to include this. Thank you for the suggestion.

**Comment by ottodobretsberger** [comment]
@ncpunt this should be enabled in v2. Please check it out and let us know if you see any issues.

**Comment by ncpunt** [comment]
Works like a charm.

        private static void Window_WindowSizeChanged(object sender, Size e)
        {
            PhotinoWindow window = sender as PhotinoWindow;

            if (size == null)
            {
                size = e;
            }
            else
            {
                double zoomx = (double)e.Width  / ((Size)size).Width  * 100;
                double zoomy = (double)e.Height / ((Size)size).Height * 100;
                double zoom   = Math.Min(zoomx, zoomy);
                window.Zoom  = (int)zoom;
            }           
        }
![1-Norm](https://user-images.githubusercontent.com/38488007/131653828-dfe2a558-07bb-406f-b576-6ce33b58b09c.jpg)
![2-Width](https://user-images.githubusercontent.com/38488007/131653838-70cd5e41-a89e-4bb6-8e67-eecffa3846b9.jpg)
![3-Height](https://user-images.githubusercontent.com/38488007/131653850-b25d9a6b-7376-4364-9c5d-e2a9574a65c1.jpg)
