### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by ncpunt** [tryphotino/photino.NET#50]
Scenario:
-published and copied the Hello demo to an Unbuntu 20.04 VM.
-Installed  .NET 5 runtime (sudo snap install dotnet-sdk --classic --channel=5.0)
-Installed WebkitGTK+ (sudo apt-get update && sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev)
-Running the app (dotnet HelloPhotino.NET1.dll)

Creating new PhotinoWindow instance.
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libPhotino.Native: cannot open shared object file: No such file or directory
   at PhotinoNET.PhotinoWindow.Photino_ctor(String title, IntPtr parentPhotinoNET, WebMessageReceivedDelegate webMessageReceivedCallback, Boolean fullscreen, Int32 x, Int32 y, Int32 width, Int32 height)
   at PhotinoNET.PhotinoWindow..ctor(String title, Action`1 configure, Int32 width, Int32 height, Int32 left, Int32 top, Boolean fullscreen)
   at HelloPhotinoApp.Program.Main(String[] args) in E:\NeoSim\Photino\HelloPhotino.NET1\Program.cs:line 21
Aborted (core dumped)

The shared libray is present: 
-runtimes/linux-x64/native/Photino.Native.so

**Comment by MikeYeager** [comment]
Hello @ncpunt,

It's most likely the .NET 5 install. We've encountered problems with snap installs as they attempt to sandbox the apps. Please try installing .NET 5 from the Microsoft download page instructions and let us know if that fixes it.

**Comment by ncpunt** [comment]
It seems that there are 3 options for installing .NET 5 (SDK or Runtime)

1) Package install
2) Snap install
3) Manual install

I initially used Snap because the package install failed with the following errors:

   Unable to locate package aspnetcore-runtime-5.0
   Couldn't find any package by glob 'aspnetcore-runtime-5.0'
   Couldn't find any package by regex 'aspnetcore-runtime-5.0'

It works with the manual install.

**Comment by MikeYeager** [comment]
Excellent! Yes, we've seen this before. The manual install seems to be the way to go on Linux. I assume the apps run now?

**Comment by ncpunt** [comment]
Yes, it runs perfectly. Next up: macOS (Big Sur).
