### ISSUE TITLE
Show with WaitForCloseAsync or other non-blocking function

### ISSUE THREAD

**Issue by 9ParsonsB** [tryphotino/photino.NET#52]
Hi,

Could you please add functionality (or sample showing) whereby you can create a PhotinoWindow and it receives events (loads page, mouse clicks works, etc.) without calling a blocking function like `WaitForClose()`

If I just call `Show()` the window shows but it never accepts [OS] events until I call `WaitForClose()`, which then blocks the current Thread/Task, which I don't want to do.

I am trying to tell Photino to close the window from C#, not from the user or the browser context. 
When calling window.Close() the thread it is called from blocks (whether or not you use `window.Invoke()` as suggested in #29)

**Comment by MikeYeager** [comment]
Please see Issue #21 for a discussion and work-arounds for this. Typically, we do want to block because, if you don't block somewhere, your app will exit.

**Comment by 9ParsonsB** [comment]
> Typically, we do want to block because, if you don't block somewhere, your app will exit.

As it stands, this makes it difficult to do other things in the same process as discussed in that issue. I think It would be useful to expose a way for the developer to choose if they want to handle when to block rather then blocking the current thread to have the window work at all.

**Comment by grofit** [comment]
Is someone able to provide an example on how these scenarios should be handled?

In my scenario I want to load the app/window up with a splash screen while lots of background loading happens, once the background loading is done im happy to block on `window.WaitForClose()` but the only way I can see to show the application/window is via `app.Run` which blocks and if I attempt to run it in `Task.Run` or similar it blows up due to memory issues.

**Comment by philippjbauer** [comment]
@grofit Can't you start up your web app in Photino with a splash screen, run your tasks in the background on a separate thread and issue a JS event into the web app that signals the process is done to route from the splash screen into the interface? Perhaps this comment is of help https://github.com/tryphotino/photino.NET/issues/21#issuecomment-797701311

**Comment by grofit** [comment]
Yeah this is what I ended up doing, passing back the window with a listener for it closing to issue shutdowns to other processes running.

**Comment by dos-ise** [comment]
Stumbled upon on this problem today since we wanted to use async main for some other reasons.

I used the extension mentioned on stackoverflow. This worked create for me.

```
public static class Extensions
{
    public static void RunSTA(this Thread thread)
    {
        thread.SetApartmentState(ApartmentState.STA); // Configure for STA
        thread.Start(); // Start running STA thread for action
        thread.Join(); // Sync back to running thread
    }
}
```

```
   static async Task Main(string[] args)
   {
            new Thread(() =>
            {
                var window = new PhotinoWindow()
                    .SetTitle(windowTitle)
                    .SetIconFile("Resource/favicon.ico")
                    // Resize to a percentage of the main monitor work area
                    //.SetUseOsDefaultSize(true)
                    .SetSize(new System.Drawing.Size(1200, 900))
                    // Center window in the middle of the screen
                    .Center()
                    // Users can resize windows by default.
                    // Let's make this one fixed instead.
                    .SetResizable(true)
                    .Load(Core.Base.Url()); // Can be used with relative path strings or "new URI()" instance to load a website.

                window.WaitForClose(); // Starts the application event loop
            }).RunSTA();
  }
```

**Comment by philippjbauer** [comment]
@dos-ise could you explain your use-case a little bit more? We're wondering wether to add this to the docs so it doesn't get lost in the issues here.

**Comment by yungfox** [comment]
hey all, I've managed to get a Blazor Server project working with a Photino window using top-level statements. I borrowed mostly from the solution proposed by @dos-ise but I had to omit the `thread.Join()` call as it would block execution. Final code looks like this:
```c#
// web server logic here, omitted for brevity

// Using a cancellation token source, so we can exit the web server later:
using var token = new CancellationTokenSource();

#if DESKTOP  // custom preprocessor directive
var window_thread = new Thread(() =>
{
    // Create the Photino window:
    var window = new PhotinoWindow()
        .SetTitle("app")
        .SetUseOsDefaultSize(false)
        .SetSize(new Size(1024, 768))
        .SetIconFile(Path.Combine("path/to/icon")
        .Center()
        .SetResizable(true)

        // ... and load the web content at the URL / port:
        .Load("http://localhost:5000");

    // Wait until the Photino window was closed:
    window.WaitForClose();

    // Cancel the webserver using the token:
    token.Cancel();
});

window_thread.SetApartmentState(ApartmentState.STA);
window_thread.Start();
//window_thread.Join();  // <-- notice the commented line here
#endif

await app.RunAsync(token.Token);
```
Does leaving out `thread.Join()` have some implications? I haven't encountered any problems so far, but I'm not too familiar with threads in C# so I'm not sure if my code has some gotchas.
