### ISSUE TITLE
First Launch Not Working

### ISSUE THREAD

**Issue by KiddoV** [tryphotino/photino.NET#53]
I just give Photino a try and I couldn't even run it:
```console
PS C:\Programming Projects\Photino-Applications\Photino-App> dotnet run
C:\Programming Projects\Photino-Applications\Photino-App\HelloPhotino.NET.csproj : error NU1202: Package Photino.NET 1.1.6 is not compatible with net50 (.NETFramework,Version=v5.0). Package Photino.NET 1.1.6 supports: netstandard2.1 (.NETStandard,Version=v2.1)
C:\Programming Projects\Photino-Applications\Photino-App\HelloPhotino.NET.csproj : error NU1202: Package Photino.NET 1.1.6 is not compatible with net50 (.NETFramework,Version=v5.0) / win7-x86. Package Photino.NET 1.1.6 supports: netstandard2.1 (.NETStandard,Version=v2.1)

The build failed. Please fix the build errors and run again.
```
Any idea what going on?
Thanks in advance!

**Comment by MikeYeager** [comment]
@KiddoV This is almost certainly an issue with installing .NET through a snap/package manager. Please see the link under Dependencies on [this page](https://docs.tryphotino.io/00a-QuickStart.md) for instructions on how to do a manual install of the framework. .NET 5 just doesn't like to run sandboxed!

**Comment by KiddoV** [comment]
@MikeYeager Sorry, I tried as the page said but still not working... same error...

**Comment by MikeYeager** [comment]
@KiddoV We just had another look at the error messages you posted and noticed Win7-x86 in on of the lines. Are you running on a 32bit OS? Currently, we only support 64bit. We have not gotten around to trying to compile for 32 bit yet.

**Comment by KiddoV** [comment]
@MikeYeager Yes I'm running it on Window 10 - 64bit. I don't know why it is output as "win7-x86". Clearly it is Win10 - 64bit.

**Comment by MikeYeager** [comment]
@KiddoV Thanks for the info. It's clearly a NuGet issue, but I don't know why you're getting it. The folder structure is a bit unusual for the HelloPhotino.NET project, but that shouldn't be an issue. What does running 'dotnet restore' output? Also, can you open the .csproj file in an editor and paste its contents here? Thanks.

**Comment by KiddoV** [comment]
@MikeYeager 
```dotnet restore```
```console
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```
```.csproj```
```html
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="1.1.6" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```
Here you go!

**Comment by MikeYeager** [comment]
@KiddoV Thank you for the info. The project file looks great. We will keep digging to find an answer for the NuGet issue.

**Comment by ottodobretsberger** [comment]
Photino v2 has been released. Please update to the new version and give it a try. Let us know if you're stull encountering that issue.
