### ISSUE TITLE
Dll was not found in some computer

### ISSUE THREAD

**Issue by tiansfather** [tryphotino/photino.NET#60]
Does the operation system lost something?
![微信图片_20210908162239](https://user-images.githubusercontent.com/16606743/132473523-69eb3873-81f6-424f-a349-1a9e7dd7d07f.png)

![微信图片_20210908162105](https://user-images.githubusercontent.com/16606743/132473356-79d3f7b3-d5e6-446e-ab28-ab2572d1f926.png)

**Comment by MikeYeager** [comment]
Please make sure that the files: Photino.Native.dll and WebView2Loader.dll are accessible. If you installed from a NuGet package, they should be in a sub-folder of the .exe, for example bin\Debug\net5.0\runtimes\win-x64\native. You can also place them in the same folder as the .exe. Also, make sure you're running on a 64 bit OS as these are 64 bit DLLs.

**Comment by tiansfather** [comment]
![image](https://user-images.githubusercontent.com/16606743/132934480-673a552d-67f6-40f8-8b9a-2c45c9eaf791.png)
![61a142ccc8675bd932096da7558ff54](https://user-images.githubusercontent.com/16606743/132934483-af9d0213-6ec1-4045-80cb-a50f8af6f7b8.png)

The dlls are in the root folder,and the system is 64 bit.

**Comment by tiansfather** [comment]
Pls tell me how to register manually,I'll try it .

**Comment by theolivenbaum** [comment]
@tiansfather did you also build your project as x64 ?

**Comment by MikeYeager** [comment]
@tiansfather To be clear, you can build your project as Any CPU or x64, however, these DLLs will only load on a 64bit Operating System.

**Comment by tiansfather** [comment]
Project was built as x64. it worked in several computer,but failed in other 2.
Here is the repository and I also published a release 
https://github.com/tiansfather/ELLDTest
May there anything wrong with the operation system?

**Comment by philippjbauer** [comment]
@tiansfather We have looked at your code and can't find any obvious problem in your code that would trigger the DLL warning. Since you've said that it runs on some machines but not others, can you determine if there are any differences between the machines? OS Versions, .NET SDK Installations, etc.? The problem might lie in the environment, not your application.

**Comment by Scraphead** [comment]
I have a laptop with with the same issue.
Program works on other machines, but not this one.

Its the same error message independent of WebView2 is installed or removed.
Only an empty PhotinoWindow with blinking terminal cursor shows up.

I have tried including Photino.Native.dll and WebView2Loader.dll in self contained executable, or next to executable. 

Both build and computer is x64. Core Runtime 6.0.1 installed.

```
System.DllNotFoundException: Dll was not found.
at PhotinoNET.PhotinoWindow.Photino_register_win32(IntPtr hInstance)
at PhotinoNET.PhotinoWindow.<>c.<.ctor>b__238_0()
at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
at PhotinoNET.PhotinoWindow..ctor(PhotinoWindow parent)
at FyndLauncher.BrowserWindow.OpenWindow()
```

```
      Time of this report: 1/20/2022, 15:12:26
         Operating System: Windows 10 Pro 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
                 Language: Norwegian Bokmål (Regional Setting: Norwegian Bokmål)
      System Manufacturer: LENOVO
             System Model: 20N8A003MX
                     BIOS: R0YET45W (1.28 ) (type: UEFI)
                Processor: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 CPUs), ~2.0GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8006MB RAM
                Page File: 7771MB used, 11498MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 144 DPI (150 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
 DirectX Database Version: 1.3.2
           DxDiag Version: 10.00.19041.0928 64bit Unicode
```

**Comment by MikeYeager** [comment]
@Scraphead @theolivenbaum @tiansfather I think the best way to troubleshoot is to use the [fuslogvw](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) tool. When run, it logs detailed information about all assembly loading at the Windows OS level. It will show exactly which assembly is failing to load and all paths used to search for it. You might also check that you're installing the Evergreen version of the WebView2 control.

**Comment by Scraphead** [comment]
@MikeYeager I am not able to get any log from fuslogvw or Fusion++ https://github.com/awaescher/Fusion

I am running as admin, and setting HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Fusion forcelog to true.

Fusion++ shows log when testing another dummy program with missing dll, but I can't get Photino to trigger a log when System.DllNotFoundException is hit.

**Comment by MikeYeager** [comment]
fuslogvw is notoriously quirky, but also incredibly useful. It used to be in the Windows SDK, but apparently it's installed with Visual Studio now and will run from the VS Terminal window. You do have to run VS 'as admin', or it won't let you change settings. Run it, then go into Settings... I've found it works best if I set a results path (C:\temp or something), and have it log everything. Turn it on, run the app, turn it off as soon as you get the exception. It doesn't seem to actually log anything until you turn it off (quirky!). Digging through the on-screen entries is extremely tedious, but if you can get the output file, you can do text searches. I would initially try the Default Log Categories and only try Native Images if you don't get the results you need.
![image](https://user-images.githubusercontent.com/7063813/150574870-1a4d22eb-f6c4-44e6-b3e5-dbab2c89573e.png)

**Comment by xaevman** [comment]
We've seen similar behavior before on machines that do not have the MSVC common C runtime installed. This is much more common on non-developer machines

The redistributable installer can be found here: https://aka.ms/vs/17/release/vc_redist.x64.exe

A better fix, IMO, is to statically link the runtime in the Photino.Native build outputs for Windows. @MikeYeager are you guys open to this?

**Comment by Scraphead** [comment]
> We've seen similar behavior before on machines that do not have the MSVC common runtime installed. This is much more common on non-developer machines
> 
> The redistributable installer can be found here: https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> A better fix, IMO, is to statically link the runtime in the Photino.Native build outputs for Windows. @MikeYeager are you guys open to this?

Can confirm that installing VC_Redist did indeed work for for both our computers with missing dll issue.

**Comment by philippjbauer** [comment]
It does make sense to us to link the DLL directly.
We will find a PC without those dev resources installed or set up a VM to test everything.

**Comment by philippjbauer** [comment]
Seems to be fixed ... I'm closing this, please re-open or post a new issue if this behavior reappears.
