### ISSUE TITLE
Chromeless windows do not display on Windows 11

### ISSUE THREAD

**Issue by 9ParsonsB** [tryphotino/photino.NET#61]
When setting `Chromeless = true` for a new `PhotinoWindow` the window does not display, but does show in the taskbar

![Photino in taskbar](https://i.imgur.com/SlzrgZV.png)

OS build: 22458.1000 (Dev Channel) & 22000.194 (Release Preview)
Edge: 95+

**Comment by MikeYeager** [comment]
This should be fixed in the new version to be published soon. It's now in testing.
