### ISSUE TITLE
Photino.NET 2.0.12 buggy?

### ISSUE THREAD

**Issue by OkayX6** [tryphotino/photino.NET#62]
Hi,

I updated the sample Photino template to version 2.0.12 from 2.0.11, and I got this when running ``dotnet run``?
Also, the text comes up in Chinese?

![image](https://user-images.githubusercontent.com/1169339/134281211-e04d7430-0a53-48b3-81a5-5cf2e3206309.png)

**Comment by philippjbauer** [comment]
We noticed an error on the macOS version of the Photino sample apps, preventing Photino to be opened on macOS. After compiling Photino.NET on macOS it worked on macOS but broke the Windows version of Photino. Please use 2.0.11 for now. Today we are trying to work through this issue and release a new version that resolves this issue on both operating systems.

**Comment by MikeYeager** [comment]
We posted a new version to NuGet yesterday that fixes this issue. Please give it a try. Thanks.

**Comment by OkayX6** [comment]
Thanks it doesn't happen anymore
