### ISSUE TITLE
SetSize(1024, 768)

### ISSUE THREAD

**Issue by solbster** [tryphotino/photino.NET#67]
Hello

When creating the PhotinoWindow and setting the size, nothing happens.

**Comment by MikeYeager** [comment]
@solbster This is a breaking change from V1.x. You have to specify .SetUseOsDefaultSize(false) or UseOsDefaultSize = false when setting a custom window size. The default is to allow the OS to size and position the window for you (which Windows and macOS do pretty well while Linux does not).
