### ISSUE TITLE
Chromeless setting cannot be used on an unitialized window.

### ISSUE THREAD

**Issue by revenz** [tryphotino/photino.NET#69]
Hi,

I have the following code

```
window.RegisterSizeChangedHandler((object sender, System.Drawing.Size size) =>
            {
                var win = (PhotinoWindow)sender;
                if (win.Maximized)
                {
                    try
                    {
                        win.SetChromeless(true);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                }
            });
```

When win.SetChromeless is called in this handler the exception "Chromeless setting cannot be used on an unitialized window." is thrown.   If I use "window" instead of "win", same thing (just incase for some reason they were different objects).

Basically I just want a way to make maximize to do a fullscreen style mode.   If I try "SetFullScreen" that works from here, however, it fullscreens on monitor 1 and not the window is opened (which in my case will always be monitor 2).

**Comment by MikeYeager** [comment]
@revenz This appears to be a typo in the error message. It now reads "Chromeless can only be set before the native window is instantiated.". We don't allow you to change the window to chromeless after it's created as this can't be supported on all platforms.
