### ISSUE TITLE
RegisterWindowClosingHandler not working on linux  (Debian)

### ISSUE THREAD

**Issue by neurodot** [tryphotino/photino.NET#72]
I succesfully ported small winform application as a multiplatform desktop app running under Photino. 
With one exception - RegisterWindowClosingHandler works on the windows, but not works on the linux. 
When I click on the X (close icon on the toolbar), „closing event“ is not fired and when I close the child window (with X), whole application is closed.  On the windows it works as expected.

**Comment by MikeYeager** [comment]
Duplicate of tryphotino/photino.Native#75
