### ISSUE TITLE
Templates fail installing

### ISSUE THREAD

**Issue by mika76** [tryphotino/photino.NET#79]
MacOS Big Sur 11.6

Running the first line of the example script `dotnet new -i TryPhotino.VSCode.Project.Templates` does not work and failes with a 

```
$ dotnet new --install TryPhotino.VSCode.Project.Templates::2.0.1
The following template packages will be installed:
   TryPhotino.VSCode.Project.Templates::2.0.1

Warning: Failed to download TryPhotino.VSCode.Project.Templates::2.0.1 from NuGet feed https://api.nuget.org/v3/index.json.
TryPhotino.VSCode.Project.Templates::2.0.1 could not be installed, download failed.
```

Also the template repository seems to have been removed from github?

**Comment by MikeYeager** [comment]
@mika76 The template repo is still on GitHub. It hasn't been modified or removed. As far as the error you're seeing, perhaps it's a transitory issue with NuGet.org? Try navigating your browser to [](https://api.nuget.org/v3/index.json) and see if it opens the file. It does for me.

**Comment by mika76** [comment]
If you go to https://www.nuget.org/packages/TryPhotino.VSCode.Project.Templates/ and click on the Project repository it tried to go to https://github.com/tryphotino/PhotinoSamples.VSCodeTemplates which gives a 404 also...

**Comment by MikeYeager** [comment]
@mika76 Interesting... it works for me. Where are you located?

**Comment by MikeYeager** [comment]
@mika76 Apparently, it's set up as a private repo. I will look into that.

**Comment by mika76** [comment]
Serbia, but I've never experienced location being an is die. Maybe some permission is set?

**Comment by mika76** [comment]
> @mika76 Apparently, it's set up as a private repo. I will look into that.

Ah good stuff 😊

**Comment by MikeYeager** [comment]
@mika76 Yes, that project and the VS Extension project are set up as private. There really isn't any source code in there as they're just packaged versions of the sample apps. We meet on Thursdays, so I'll bring this up Thursday and see if there is a reason to not make these public. Were you able to get the NuGet package? That's the most important thing and unrelated to this issue.

**Comment by mika76** [comment]
I'll try it again in a bit and let you know...

**Comment by mika76** [comment]
Interesting, works on my Windows VM but not on the Mac. Probably some setting on my side...

**Comment by mika76** [comment]
FYI: https://github.com/dotnet/templating/issues/4176 - managed to get a verbose output using an environment variable (wish I knew about this before) - seems it's my .templateengine directory permissions which are making it fail for all template installs. So nothing on your side.

Thanks for you help @MikeYeager
