### ISSUE TITLE
Minimum window size

### ISSUE THREAD

**Issue by NewMySQL** [tryphotino/photino.NET#83]
How can I specify minimum window size? 

If you restrict through WindowSizeChanged, by reassigning sizes, then it looks terrible in the final form, the window context starts jumping when it is reduced.

**Comment by MikeYeager** [comment]
Good feature request. We'll put it on the list. It will have to happen in Photino.Native and be implemented here as well.

**Comment by LauraWebdev** [comment]
@NewMySQL How did you implement your workaround solution, I'm in dire need to set a minimum width/height for an application.

**Comment by philippjbauer** [comment]
@LauraWebdev you can use the `.RegisterSizeChangedHandler(WindowSizeChanged)` with a delegate function to resize if a certain minimum size was reached.

We still need to implement configuration properties for MinHeight/Width and MaxHeight/Width and enable this behavior in the native implementation for all OS.

**Comment by LauraWebdev** [comment]
@philippjbauer that does seem to work, but only for a few calls until it can be resized again. (Unless I'm doing something completely wrong here).

```csharp
.RegisterSizeChangedHandler((sender, size) =>
{
    var window = (PhotinoWindow?)sender;
    
    if (size.Width < 600)
    {
        Console.WriteLine("Window Width Too Small");
        window?.SetWidth(600);
    }
    if (size.Height < 400)
    {
        Console.WriteLine("Window Height Too Small");
        window?.SetHeight(400);
    }
})
```

Console output does show it's called on resize, but after clipping the window at W600 / H400, it doesn't do it anymore. I s that worth a bug issue?

https://github.com/tryphotino/photino.NET/assets/7365286/65741a3c-91a9-4711-8f21-ebd6a9c3c0cc

**Comment by LauraWebdev** [comment]
This is on Ubuntu (I believe it's 20.04 LTS).

**Comment by LauraWebdev** [comment]
@philippjbauer just checked and it doesn't happen on Windows 11 either.

**Comment by philippjbauer** [comment]
I can reproduce the error on Ubuntu as well. From what I can tell this might be an issue with the GTK event queue that can't handle the deluge of resize commands that pour in from this fairly simple implementation. I've played around with debouncing the resize event and forcing a redraw of the window but the results are not great.

The way to implement this in Linux is to add the following GTK code to the Linux native library:

```cplusplus
void Photino::SetMinimumSize(int minWidth, int minHeight)
{
    GdkGeometry hints;
    hints.min_width = minWidth;
    hints.min_height = minHeight;
    hints.min_aspect = 0.0;
    hints.max_aspect = 0.0;

    gtk_window_set_geometry_hints(GTK_WINDOW(_window), NULL, &hints, GDK_HINT_MIN_SIZE);
}
```

This is tested code that works. We will have to include equivalent code for WIN32 and Cocoa (macOS) native library and expose the SetMinimumSize method in the C# environment.

The implementation for WIN32 might look like:

```cplusplus
void SetMinimumSize(HWND hWnd, int minWidth, int minHeight)
{
    RECT rect;
    GetWindowRect(hWnd, &rect);

    int width = rect.right - rect.left;
    int height = rect.bottom - rect.top;

    int newWidth = max(width, minWidth);
    int newHeight = max(height, minHeight);

    SetWindowPos(hWnd, NULL, 0, 0, newWidth, newHeight, SWP_NOMOVE | SWP_NOZORDER);
}
```

and for macOS:

```cplusplus
void SetMinimumSize(NSWindow* window, CGFloat minWidth, CGFloat minHeight)
{
    NSSize minSize = NSMakeSize(minWidth, minHeight);
    [window setMinSize:minSize];
}
```

Equivalent SetMaximumSize methods should be introduced to compliment the minimum size constraint functionality.

**Comment by MikeYeager** [comment]
This has been implemented at the Photino.Native level and surfaced at the Photino.NET level. It will be in the next release.
