### ISSUE TITLE
How to load JS content in script tag that has `type="module"`?

### ISSUE THREAD

**Issue by drk-mtr** [tryphotino/photino.NET#93]
This is a question rather than a bug, but I feel it might be relevant to others so I'm asking here just in case you want me to put in a PR to update documentation once I understand the solution.

1. I create a template project using `dotnet new photinoapp`
2. I create a `test.js` file in `./wwwroot` with content `console.log('testing')`
3. I reference the script in `index.html` with `<script src="test.js"></script>`
4. I run the app with `dotnet run` and press F12 and I can see "testing" in the console as expected
5. I specify that this JS file should be loaded as a module i.e. I change to `<script type="module" src="test.js"></script>`
6. I run the app with `dotnet run` and press F12 and see the error below

`Access to script at 'file:///C:/Projects/{myFolderStructure}/test.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, https, chrome-untrusted.`

Is there a suggested approach for handling this?

**Comment by ottodobretsberger** [comment]
You could try loading the file using a custom schema (which you need to register), and then use something like "app://test.js" to access the file .

**Comment by drk-mtr** [comment]
Thanks for the response! I gave that a go but didn't have much luck unfortunately. The handler I wrote looked like this:

```cs
        .RegisterCustomSchemeHandler("app", (object sender, string scheme, string url, out string contentType) =>
        {
            contentType = "text/javascript";
            var filename = url.Replace("app://", "");
            return new MemoryStream(Encoding.UTF8.GetBytes(File.ReadAllText($"{filename}")));
        })
```

That worked when I omitted `type="module"` from the script tag, but not when I included it. Having looked into it more, I'm guessing it's normal browser security that's preventing me here i.e. it sees it as an external resource therefore it's trying to apply the same origin policy.

The only way I was able to get it to work eventually was to serve the javascript file I wanted using a local server, with https enabled, then reference this localhost address from the html. I couldn't get a custom handler working for this for some reason.

**Comment by richardschoen** [comment]
I had a similar issue which has caused me to pause usage until I can figure it out.

**Comment by drk-mtr** [comment]
@richardschoen Out of interest what was your use case?

In my case I wanted to make the UI using web components made with lit. I found I can work around this in the meantime using a framework (Svelte JS for me, but could be e.g. Vue or Angular) as my app root, then just importing my web components into that.

**Comment by richardschoen** [comment]
My use case was mainly just wanting to know how to load a JS library of my own functions for usage. And potentially other local Javascript/CSS files as needed.

**Comment by drk-mtr** [comment]
Fair, sounds like we're in the same boat. I think it is possible to work around this by packaging modules using a build tool like rollup or webpack, but obviously the downside is that makes your build chain more complex.

**Comment by simevo** [comment]
There are other scenarios where this may come up, for us it is retrieving images and JS files with XHR or fetch API... and this issue: #70.

I think there are two solutions:

1. implement in `photino.Native` something similar to https://github.com/MicrosoftEdge/WebView2Feedback/issues/530 i.e. add a method similar to [CoreWebView2.SetVirtualHostNameToFolderMapping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping) to set a mapping between a virtual host name and a folder path so that `wwwroot/index.html` is accessible as `Uri("http://appassets.example/index.html")`

2. or bundle in the photino-packaged app a webserver that merely serves the static files in `wwwroot` at `http://localhost:3000` (any hints how to do that in one of the photino samples would be appreciated!)

**Comment by MikeYeager** [comment]
@simevo Thanks for your thoughts on this. For option 1, we'd have to look into if and how to do this with the browser controls used on Mac and Linux as well. For option 2, we do have samples that host API calls with ASP.NET, which would also cover serving files. There are lots of other options to run a more light-weight web server, but this is an all .NET solution with no 3rd party dependencies.

**Comment by richardschoen** [comment]
If you were to bundle in a Kestral localhost web server instance into a compiled app automatically that would definitely solve the issue of serving local files. The web server could simply be spun up as a background thread on app startup to serve files on the specific local file system. I've done this concept on Windows and Linux and I'm sure it would probably work on Mac as well.   

I'm currently looking in to using Electron because of the lack of being able to serve up local JS and other files with Photino currently.  I can post a code example if you need one on starting a local HTTP server inside of a .Net executable.

**Comment by simevo** [comment]
Hi! thanks for the comments.

Indeed option 1 is complex, from a quick lookup I can find no way to configure webkit to map a virtual host to a dir ...

I'd really appreciate if you could share an example of serving files with ASP.NET or any other lightweight http server!

Some time ago I had done something similar within a Qt C++ app, starting a separate process that runs webpack's builtin web server:  https://gitlab.com/simevo/theia-app/-/blob/master/main.cpp#L81 (with that approach though I have trouble detecting when the nodejs webserver is ready).

**Comment by richardschoen** [comment]
Here's a sample self-hosted web service and web server encapsulated in a WinForms app.

https://github.com/richardschoen/SelfHostedWebServiceSample1

**Comment by ottodobretsberger** [comment]
You could also look at the sample where we serve WebAPI from a webserver within Photino.NET.

**Comment by richardschoen** [comment]
@ottodobretsberger Where would that sample be ?

**Comment by MikeYeager** [comment]
@richardschoen Try this one: https://github.com/tryphotino/photino.Samples/tree/master/Photino.HelloPhotino.TestBench It uses ASP.NET to host WebAPI, but it can also host web pages.

**Comment by 1970633640** [comment]
Because normal javascript works fine. I have a simple hack to bypass CORS limits.

make a new js file:
```
function addScript() {
    var s = document.createElement('script');
    s.setAttribute('src', "data:text/javascript;base64,REPLACE");
    s.setAttribute('type', 'module');
    document.head.appendChild(s);
}
```
and replace "REPLACE" with base64 encoded js module code.

Then, add this js file to the HTML page
```
<script src="path/to/the.js"></script>
```

and call ```addScript()``` in the HTML page.

**Comment by manuel3108** [comment]
For anyone looking why the linked code is not compiling anymore: Apparently the server has been extracted to a own package. You can find it here: https://www.nuget.org/packages/Photino.NET.Server

The link above is referencing an outdated version of the current sample. Look here for the most updated one: https://github.com/tryphotino/photino.Samples/blob/master/Photino.HelloPhotino.StaticFileServer/Program.cs#L12
