### ISSUE TITLE
Is it possible to bundle the frontend code inside the .exe?

### ISSUE THREAD

**Issue by MarioGK** [tryphotino/photino.NET#97]
Basically what i am asking is if we can bundle the html,css,js files inside the .exe so we trully have a single.exe like Tauri does.

**Comment by richardschoen** [comment]
If you're using Tauri what's the appeal of Photino ?   

I hadn't heard of Tauri until I saw this post.

Curious to hear comparisons, good and bad.

**Comment by MarioGK** [comment]
> If you're using Tauri what's the appeal of Photino ?
> 
> I hadn't heard of Tauri until I saw this post.
> 
> Curious to hear comparisons, good and bad.

I am not using Tauri, I just mentioned it so it would be easier to understand as they already have this feature.

Well I am a bit biased because I am a C# fanboy, but Tauri has many awesome features, but I really hate rust for simple apps like wep desktop apps.

**Comment by richardschoen** [comment]
Yep, C# is my favorite jam as well.

**Comment by stevesobol** [comment]
There are ways to do this with Win32 applications. Basically, the PE format allows you to put data at the end of an EXE, essentially packaging it in with the binary. Not sure if .NET allows this, though. Not sure if it's needed, either.

**Comment by MikeYeager** [comment]
I think this is mainly a feature of .NET, not Photino. https://blog.inedo.com/dotnet/self-contained-applications The .NET files and the Photino.Native file would all be packaged together. I'm not sure how content files would be handled though. I think Photino.Native would need to allow the use of contained resources in place of loose files to fully allow this though. For now, I think a 3rd party tool such as https://www.boxedapp.com/ can achieve what you want right now.

**Comment by Scraphead** [comment]
If it helps anyone, this is how I did it.
We used [EmbedIO](https://github.com/unosquare/embedio) to start a web server with the application.
The static web site is placed in a Resources folder in project.

EmbedIO 
```csharp
WebServer ws = new WebServer(o => o.WithUrlPrefix("http://localhost:1234").WithMode(HttpListenerMode.EmbedIO));
var resourceFolder = GetType().Namespace + ".Resources";
var assembly = GetType().Assembly;
ws.WithModule(new FileModule("/", new ResourceFileProvider(assembly, resourceFolder)) 
    { DirectoryLister = DirectoryLister.Html });
ws.RunAsync();

// Photino needs to open website "http://localhost:1234"
```

Tell .csproj to include Resources folder with all files to be embedded.
```
    <ItemGroup>
        <EmbeddedResource Include="Resources\**" />
    </ItemGroup>
```

With .net 6 I can then build project as a standalone executable with EmbedIO, photino, and the resources.

```
dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained true -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
```


I think the only other minor fix was to set PhotinoWindow IconFile. Since the icon was now inside resources folder, I had to copy it to system temp folder first.

```csharp
var iconResourcePath = "Resources.favicon.ico";
if (Tools.ContainsResource(iconResourcePath))
{
    var launcherIconTempPath = Path.Combine(Path.GetTempPath(), "MyApplication.ico");
    Tools.CopyFromResources(iconResourcePath, launcherIconTempPath);
    myPhotinoWindow.SetIconFile(launcherIconTempPath);
}
```

Tools to copy file from resources folder
```csharp
public static void CopyFromResources(string resourcePath, string filePath)
{
    var assembly = System.Reflection.Assembly.GetEntryAssembly();
    
    //Goes through all files in manifest and finds first match
    var assemblyResourcePath = assembly?.GetManifestResourceNames()
        .FirstOrDefault(res => res.EndsWith(resourcePath));
    if (assemblyResourcePath != null)
    {
        using (var resStream = assembly.GetManifestResourceStream(assemblyResourcePath))
        {
            //Ensure directory
            var directoryName = Path.GetDirectoryName(filePath);
            if (Directory.Exists(directoryName) == false)
                Directory.CreateDirectory(directoryName);
            
            using(var fileStream = new FileStream(filePath, FileMode.Create))
            {
                resStream?.CopyTo(fileStream);
            }
        }
    }
}

public static bool ContainsResource(string resourcePath)
{
    var assembly = System.Reflection.Assembly.GetEntryAssembly();
    
    //Goes through all files in manifest and finds first match
    var assemblyResourcePath = assembly?.GetManifestResourceNames()
        .FirstOrDefault(res => res.EndsWith(resourcePath));

    return assemblyResourcePath != null;
}
```

**Comment by Scraphead** [comment]
No, I did not check out Kestral, I might look into that or [GenHTTP](https://github.com/Kaliumhexacyanoferrat/GenHTTP) if I see a need to move on from EmbedIO.

**Comment by philippjbauer** [comment]
@richardschoen @Scraphead We are about to release an update to Photino.NET that includes a Kestrel-based (ASP.NET's bundled) WebServer that can serve files either from embedded resources (dll), the physical filesystem or both. The developer can either drop files into the FS based `./wwwroot` or into the embedded resource webroot folder `./Resources/wwwroot`. Files within `./Resources` that are not in the wwwroot-subfolder can then be accessed through the method described by Scraphead.

A sample will soon be available in the Photino.Samples project as Photino.HelloPhotino.StaticFileServer.

**Comment by philippjbauer** [comment]
@MarioGK we just released a new version of Photino.NET that includes a static file server. If you build your web interface into the `./Resources/wwwroot` folder, and enable the generation of manifest files in your project file the server will try to use the embedded files before falling back to the file-system based `./wwwroot` folder. Please take a look at the `Photino.HelloPhotino.React` sample in the Photino.Samples repo.
