### ISSUE TITLE
Resizable on mode chromeless?

### ISSUE THREAD

**Issue by obius-byte** [tryphotino/photino.NET#98]
`.SetChromeless(true).SetResizable(true)`
Window resizable is not working

`.SetChromeless(false).SetResizable(true)`
Window resizable is working

`<PackageReference Include="Photino.NET" Version="2.1.11" />`
Platform: Windows 10 x64 

Is it possible for both options to work at the same time?

**Comment by MikeYeager** [comment]
@obius-byte The window should still be re-sizable programmatically, but without window chrome, it can't be re-sized by the user. That's actually the point of having the chrome. It's to give the user something to grab and drag. Usually, the point of eliminating the chrome is for things like kiosks where you want to disable this functionality. If you want to allow the user to re-size without chrome, as is often the case when the user wants to draw their own title bar and other chrome, the JavaScript can make programmatic calls to change the size of the window as the user drags the JavaScript objects. Does that address your concerns?

**Comment by obius-byte** [comment]
I understood the meaning. Thank you for the clarification!

**Comment by ivanjx** [comment]
@MikeYeager is there any example of dragging and resizing via the javascript? in my case i want to use blazor but if js is required then im fine with it. thanks.
